# Generated by Django 4.1.7 on 2023-07-21 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationcategory",
            name="category_name",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="operationtype",
            name="type_name",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
