# Generated by Django 4.1.7 on 2023-07-25 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounting", "0002_alter_operationcategory_category_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubtreasury",
            name="operation_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="accounting.operationcategory",
            ),
        ),
        migrations.AlterField(
            model_name="clubtreasury",
            name="operation_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="accounting.operationtype",
            ),
        ),
        migrations.AlterField(
            model_name="clubtreasury",
            name="performed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
