# Generated by Django 4.1.7 on 2023-09-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClubbingSpot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_spot", models.CharField(max_length=100)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("water_access", models.BooleanField()),
                ("description", models.CharField(max_length=255)),
                ("kml_file", models.FileField(upload_to="kml_files")),
            ],
        ),
    ]
