# Generated by Django 4.1.7 on 2023-06-06 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="user_birthday",
            field=models.DateField(blank=True, null=True),
        ),
    ]
