# Generated by Django 4.1.7 on 2023-03-27 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EquipmentsCategories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "equipment_category_name",
                    models.CharField(max_length=20, unique=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Equipments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("equipment_name", models.CharField(max_length=50)),
                ("weight_of_equipment_kg", models.FloatField()),
                ("photo_of_equipment", models.CharField(max_length=255)),
                ("now_booked", models.BooleanField(default=False)),
                (
                    "equipment_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="equipment_accounting.equipmentscategories",
                    ),
                ),
            ],
        ),
    ]
