# Generated by Django 4.1.7 on 2023-06-11 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "equipment_accounting",
            "0003_remove_equipments_now_booked_equipments_current_user_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipments",
            name="equipment_category",
        ),
        migrations.AddField(
            model_name="equipments",
            name="equipment_category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="equipment_accounting.equipmentscategories",
            ),
        ),
    ]
