# Generated by Django 4.1.7 on 2023-06-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment_accounting", "0004_remove_equipments_equipment_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipments",
            name="equipment_category",
        ),
        migrations.AddField(
            model_name="equipments",
            name="equipment_category",
            field=models.ManyToManyField(
                to="equipment_accounting.equipmentscategories"
            ),
        ),
    ]
