# Generated by Django 4.1.7 on 2023-06-13 03:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "equipment_accounting",
            "0006_rename_booking_date_equipmentbooking_booking_date_from_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipmentbooking",
            name="booking_date_to",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
